<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * QuizzRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuizzRepository extends EntityRepository
{
	function verifyDates($dateStart,$dateEnd,$idQuizz = null)
	{
		$query = $this->createQueryBuilder('q')
					  ->select('COUNT(q)');

		$parameters = array(
			'dateS' => $dateStart,
			'dateE' => $dateEnd
		);

		$query->where($query->expr()->orX(
			$query->expr()->andX(
				$query->expr()->lte('q.dateStart',':dateS'),
				$query->expr()->gt('q.dateEnd',':dateS')
			),
			$query->expr()->andX(
				$query->expr()->lt('q.dateStart',':dateE'),
				$query->expr()->gte('q.dateEnd',':dateE')
			),
			$query->expr()->andX(
				$query->expr()->gte('q.dateStart', ':dateS'),
				$query->expr()->lte('q.dateEnd',':dateE')
			)
		));

		if($idQuizz != null)
		{
			$query->andWhere('q.id <> :idQuizz');
			$parameters['idQuizz'] = $idQuizz;
		}

		$query->setParameters($parameters);

		return $query->getQuery()->getSingleScalarResult();
	}

	function getCurrentQuizz()
	{
		$now = new \DateTime();

		$query = $this->createQueryBuilder('q');
		$query->where($query->expr()->andX(
			$query->expr()->lte('q.dateStart',':now'),
			$query->expr()->gt('q.dateEnd',':now')
		))
			->setParameters(array(
				'now' => $now
			));

		return $query->getQuery()->getOneOrNullResult();
	}

	function getLastQuizz()
	{
		$now = new \DateTime();

		$query = $this->createQueryBuilder('q');
		$query->where(
				$query->expr()->lt('q.dateEnd',':now')
			)
			->andWhere('q.active = 1')
		    ->setParameters(array(
			   'now' => $now
	    ));

		return $query->getQuery()->getOneOrNullResult();
	}

	function getOldQuizz()
	{
		$now = new \DateTime();

		$query = $this->createQueryBuilder('q');
		$query->where(
			$query->expr()->lt('q.dateEnd',':now')
		)
		      ->andWhere('q.active = 1')
		      ->setParameters(array(
			      'now' => $now
		      ));

		return $query->getQuery()->getResult();
	}
}
